/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/code'
import { Route as EdaRouteImport } from './routes/eda'
import { Route as ImbalanceRouteImport } from './routes/imbalance'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PredictRouteImport } from './routes/predict'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const EdaRoute = EdaRouteImport.update({
  id: '/eda',
  path: '/eda',
  getParentRoute: () => rootRouteImport,
} as any)
const ImbalanceRoute = ImbalanceRouteImport.update({
  id: '/imbalance',
  path: '/imbalance',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/eda': typeof EdaRoute
  '/imbalance': typeof ImbalanceRoute
  '/models': typeof ModelsRoute
  '/pipeline': typeof PipelineRoute
  '/predict': typeof PredictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/eda': typeof EdaRoute
  '/imbalance': typeof ImbalanceRoute
  '/models': typeof ModelsRoute
  '/pipeline': typeof PipelineRoute
  '/predict': typeof PredictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/eda': typeof EdaRoute
  '/imbalance': typeof ImbalanceRoute
  '/models': typeof ModelsRoute
  '/pipeline': typeof PipelineRoute
  '/predict': typeof PredictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/code' | '/eda' | '/imbalance' | '/models' | '/pipeline' | '/predict'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/code' | '/eda' | '/imbalance' | '/models' | '/pipeline' | '/predict'
  id:
    | '__root__'
    | '/'
    | '/code'
    | '/eda'
    | '/imbalance'
    | '/models'
    | '/pipeline'
    | '/predict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  EdaRoute: typeof EdaRoute
  ImbalanceRoute: typeof ImbalanceRoute
  ModelsRoute: typeof ModelsRoute
  PipelineRoute: typeof PipelineRoute
  PredictRoute: typeof PredictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eda': {
      id: '/eda'
      path: '/eda'
      fullPath: '/eda'
      preLoaderRoute: typeof EdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imbalance': {
      id: '/imbalance'
      path: '/imbalance'
      fullPath: '/imbalance'
      preLoaderRoute: typeof ImbalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  EdaRoute: EdaRoute,
  ImbalanceRoute: ImbalanceRoute,
  ModelsRoute: ModelsRoute,
  PipelineRoute: PipelineRoute,
  PredictRoute: PredictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
